image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'


variables:
  TF_IN_AUTOMATION: "true"
  PLAN: plan.tfplan
  JSON_PLAN_FILE: tfplan.json

before_script:
  - rm -rf .terraform
  - terraform --version
  - mkdir -p ./credentials
  - echo $SERVICEACCOUNT | base64 -d > ./credentials/dev.json
  - export TF_VAR_db_user=$db_user
  - export TF_VAR_db_pass=$db_pass
  - terraform init

stages:
  - validate
  - plan
  - apply

validate:
  stage: validate
  script:
    - terraform validate
    - terraform fmt -check=true
  only:
    - branches

merge review:
  stage: plan
  script:
    - terraform plan -out=$PLAN
    - "terraform show --json $PLAN | convert_report > $JSON_PLAN_FILE"
  artifacts:
    name: plan
    paths:
      - $PLAN
    reports:
        terraform: $JSON_PLAN_FILE
  only:
    - merge_requests
  except:
    - schedules

plan production:
  stage: plan
  script:
    - terraform plan -out=$PLAN
    - "terraform show --json $PLAN | convert_report > $JSON_PLAN_FILE"
  artifacts:
    name: plan
    paths:
      - $PLAN
    reports:
        terraform: $JSON_PLAN_FILE
  only:
    - master
  except:
    - schedules
  resource_group: production

apply:
  stage: apply
  script:
    - terraform apply -input=false $PLAN
  dependencies:
    - plan production
  only:
    - master
  except:
    - schedules
  resource_group: production
